---
- name: Manage OpenAFS buildbot master
  hosts: openafs_buildbot_masters
  collections:
    - openafs_contrib.buildbot
  tasks:
    - import_role:
        name: buildbot_master

    - name: "Update README file."
      template:
        src: README.j2
        dest: README
        mode: "0644"

  post_tasks:
    - name: "Query buildbot status."
      command:
        cmd: .local/bin/buildbotctl status
      changed_when: false
      register: results_buildbotctl_status

    - name: "Query buildbot version."
      command:
        cmd: .local/bin/buildbot --version
      changed_when: false
      register: results_buildbot_version

    - debug:
        msg: |
          {{ results_buildbotctl_status.stdout }}
          {{ results_buildbot_version.stdout }}
