---
- name: Manage OpenAFS buildbot master
  hosts: openafs_buildbot_masters
  collections:
    - openafs_contrib.buildbot
  tasks:
    - import_role:
        name: buildbot_master

    - name: "Update README file."
      template:
        src: README.j2
        dest: README
        mode: "0644"
