---
- name: Lookup master url
  hosts: all
  tasks:
    - name: Lookup master url
      set_fact:
        afsbotcfg_url: "http://{{ hostvars['test-master']['ansible_default_ipv4']['address'] }}:{{ afsbotcfg_www_port }}/"
      when: afsbotcfg_www_port is defined

- import_playbook: ../../openafs_buildbot.yaml

- name: Deploy test workers
  hosts: openafs_buildbot_workers
  vars:
    buildbot_master_host: "{{ hostvars['test-master']['ansible_default_ipv4']['address'] }}"
    buildbot_master_port: 9989
    buildbot_worker_password: "{{ lookup('ini', '{{ buildbot_worker_name }} section=workers file={{ passwords_ini }}') }}"
  tasks:
    - import_role:
        name: openafs_contrib.openafs.openafs_devel

    - import_role:
        name: openafs_contrib.buildbot.buildbot_worker

- name: Show master url.
  hosts: openafs_buildbot_masters
  tasks:
    - debug:
        msg: "Test master URL is {{ afsbotcfg_url }}"
