---
dependency:
  name: galaxy
# Driver settings are in .config/molecule/config.yml
platforms:
  - name: test-master
    box: generic/centos7
    proxmox_template_name: centos7
    groups:
      - openafs_buildbot_masters
  - name: test-bot01
    box: generic/alma9
    proxmox_template_name: alma9
    groups:
      - openafs_buildbot_workers
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 0
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    group_vars:
      all:
        buildbot_test : true
        buildbot_project: openafs
        passwords_ini: ${MOLECULE_PROJECT_DIRECTORY}/files/passwords.ini
        ansible_shell_allow_world_readable_temp: true
      openafs_buildbot_masters:
        buildbot_master_gerrit_ident: "{{ lookup('env', 'GERRIT_IDENT') or '${MOLECULE_PROJECT_DIRECTORY}/files/gerrit' }}"
        buildbot_master_have_sudo: no
        buildbot_master_sqlalchemy_version: '==1.4.28'
        buildbot_master_buildbot_version: '==3.5.0'
        buildbot_master_config_templates:
          - ${MOLECULE_PROJECT_DIRECTORY}/templates/master.cfg.j2
          - ${MOLECULE_PROJECT_DIRECTORY}/templates/forcegerritbuild.py.j2
          - ${MOLECULE_PROJECT_DIRECTORY}/templates/email_templates.py.j2
          - ${MOLECULE_PROJECT_DIRECTORY}/templates/passwords.ini.j2
          - ${MOLECULE_PROJECT_DIRECTORY}/templates/make-rpm-workspace.sh.j2
          - ${MOLECULE_PROJECT_DIRECTORY}/templates/unpack-dkms-rpm.sh.j2
      openafs_buildbot_workers:
        buildbot_worker_admin: "tycobb@yoyodyne.com"
    host_vars:
      test-master:
        # Note: afsbotcfg_url (buildbotURL) is set in the converge playbook.
        afsbotcfg_title: 'Test'
        afsbotcfg_summary_title: "Test - OpenAFS Buildbot Coordinator"
        afsbotcfg_www_port: 8011
        afsbotcfg_build_delay: 30
        afsbotcfg_gerrit_url: "${GERRIT_URL-:https//gerrit.openafs.org}"
        afsbotcfg_repo: "${GERRIT_REPO:-git://gerrit.openafs.org/openafs.git}"
        afsbotcfg_gerrit_server: "${GERRIT_SERVER:-gerrit.openafs.org}"
        afsbotcfg_gerrit_ssh_port: 29418
        afsbotcfg_gerrit_user: "${GERRIT_USER:-buildbot}"
        afsbotcfg_gerrit_ident: "{{ buildbot_master_gerrit_ident | basename }}"
        afsbotcfg_email_from: "buildbot@openafs.MIT.EDU"
        afsbotcfg_notify_list:
          - "builders":
              - "linux-rc-x86_64"
            "recipients":
              - "root@localhost.localdomain"
      test-bot01:
        buildbot_worker_name: alma9-amd64-rpm
verifier:
  name: ansible
