---
driver:
  name: vagrant

platforms:
  - name: afsbotcfg-master
    box: generic/centos7
    groups:
      - openafs_buildbot_masters

  - name: afsbotcfg-alma-worker
    box: generic/alma9
    groups:
      - openafs_buildbot_workers

  - name: afsbotcfg-debian-worker
    box: generic/debian11
    groups:
      - openafs_buildbot_workers

  - name: afsbotcfg-ubuntu-worker
    box: generic/ubuntu2004
    groups:
      - openafs_buildbot_workers

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    host_vars:
      afsbotcfg-alma-worker:
        worker_name: "alma9-amd64"
        ansible_python_interpreter: "/usr/bin/python3"
      afsbotcfg-debian-worker:
        worker_name: "debian11-amd64"
        ansible_python_interpreter: "/usr/bin/python3"
      afsbotcfg-ubuntu-worker:
        worker_name: "ubuntu20-amd64"

    group_vars:
      all:
        afsbotcfg_version: "1.4.0"
        afsbotcfg_sqlalchemy_version: "==1.4.28"
        afsbotcfg_buildbot_version: "==3.5.0"
        afsbotcfg_project:
          name: "openafs"
          title: "OpenAFS Buildbot"
          summary_title: "The OpenAFS Buildbot Coordinator"
          db_url: "sqlite:///state.sqlite"
          url: "https://buildbot.openafs.org/"
          www_port: 8011
          pb_port: 9989
          email_from: "buildbot@openafs.MIT.EDU"
          repo: "git://gerrit.openafs.org/openafs.git"
          start_delay: 30
          branches:
            dev: "master"
            stable: "openafs-stable-1_8_x"
            oldstable: "openafs-stable-1_6_x"
          janitor:
            log_horizon: 4
            day_of_week: 6
            hour: 12
          nightly:
            dev: 13
            stable: 14
            oldstable: 15

        afsbotcfg_admin_passwords:
          - ["admin@example.com", "secret"]

        afsbotcfg_worker_passwords:
          alma9-amd64: "secret"
          debian11-amd64: "secret"
          ubuntu20-amd64: "secret"

        afsbotcfg_workers:
          alma9-amd64:
            notify: "admin@example.com"
          debian11-amd64:
            notify: "admin@example.com"
          ubuntu20-amd64:
            notify: "admin@example.com"

        afsbotcfg_builders:
          - scheduler: nightly
            os: alma9
            cc: gcc
            arch: amd64
            branch: dev
            worker: alma9-amd64
            factory:
              name: UnixBuild

          - scheduler: nightly
            os: debian11
            cc: gcc
            arch: amd64
            branch: dev
            worker: debian11-amd64
            factory:
              name: UnixBuild
              args:
                configure: >-
                  --enable-transarc-paths --enable-checking
                target: dest
              env:
                CFLAGS: >-
                  -Wno-error=format-truncation -Wno-error=format-overflow -Wno-error=restrict
                  -Wno-error=array-bounds -Wno-error=implicit-function-declaration

          - scheduler: nightly
            os: ubuntu20
            cc: gcc
            arch: amd64
            branch: dev
            worker: ubuntu20-amd64
            factory:
              name: UnixBuildAndTest

verifier:
  name: ansible
