---
driver:
  name: vagrant

platforms:
  - name: afsbotcfg-master
    box: generic/centos7
    groups:
      - openafs_buildbot_masters

provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 0
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    group_vars:
      openafs_buildbot_masters:
        afsbotcfg_version: "${AFSBOTCFG_VERSION}"
        afsbotcfg_sqlalchemy_version: "==1.4.28"
        afsbotcfg_buildbot_version: "==3.5.0"
        _merge:
          afsbotcfg_project:
            title: "Molecule Test"
            summary_title: "Molecule Test Buildbot"
          afsbotcfg_gerrit:
            keysdir: "${MOLECULE_SCENARIO_DIRECTORY}/files/ssh"
            ident: "test"
        _override:
          afsbotcfg_admin_passwords:
            - ["admin@example.com", "secret"]
          afsbotcfg_worker_passwords:
            __default__: "secret"

verifier:
  name: ansible
