---
name: "openafs"
title: "OpenAFS Buildbot"
summary_title: "The OpenAFS Buildbot Coordinator"
db_url: "sqlite:///state.sqlite"
url: "https://buildbot.openafs.org/"
www_port: 8011
pb_port: 9989
email_from: "buildbot@openafs.MIT.EDU"
repo: "git://gerrit.openafs.org/openafs.git"
start_delay: 30

# Long term branch names.
branches:
  dev: "master"
  stable: "openafs-stable-1_8_x"
  oldstable: "openafs-stable-1_6_x"

# Nightly build times.
nightly:
  dev: 1
  stable: 2
  oldstable: 3

# Delete build logs older than four weeks on Sunday at 12:00PM (noon).
janitor:
  log_horizon: 4
  day_of_week: 6
  hour: 12
